//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurumsal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urunler
    {
        public int IID { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> Fiyati { get; set; }
        public string Materyal { get; set; }
        public string Resmi { get; set; }
        public Nullable<int> Encok { get; set; }
        public Nullable<int> Yeni { get; set; }
    }
}
